'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class DefaultVertical

	''' <summary>
	''' form2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form2 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ProgressControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

	''' <summary>
	''' Spl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Spl As Global.DevExpress.Web.ASPxSplitter.ASPxSplitter

	''' <summary>
	''' SCC3 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCC3 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' LogoLink control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected LogoLink As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' TIC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TIC As Global.DevExpress.ExpressApp.Web.Controls.ThemedImageControl

	''' <summary>
	''' SAC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' ShC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ShC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' SCC4 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCC4 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' NC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected NC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer

	''' <summary>
	''' TRP control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TRP As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

	''' <summary>
	''' PanelContent1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

	''' <summary>
	''' VTC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected VTC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' DAC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' SCC5 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCC5 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' TB control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TB As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' VIC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected VIC As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

	''' <summary>
	''' VCC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected VCC As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

	''' <summary>
	''' VHC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected VHC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

	''' <summary>
	''' RNC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected RNC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' SCC6 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCC6 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' EMA control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected EMA As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' SCC7 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCC7 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' ErrorInfo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

	''' <summary>
	''' VSC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected VSC As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

	''' <summary>
	''' QC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected QC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.QuickAccessNavigationActionContainer

	''' <summary>
	''' SCC10 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SCC10 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' InfoMessagesPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' AIC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected AIC As Global.DevExpress.ExpressApp.Web.Controls.AboutInfoControl
End Class
